// import 'echarts/lib/chart/bar'
// import 'echarts/lib/chart/pie'
// import 'echarts/lib/chart/line'
// import 'echarts/lib/chart/lines'
// import 'echarts/lib/component/legend'
// import 'echarts/lib/component/legendScroll'
// import 'echarts/lib/component/tooltip'
// import 'echarts/lib/component/title'
// import 'echarts/lib/component/markPoint'
// import 'echarts/lib/component/markLine'
// import 'echarts/lib/component/markArea'
// import 'echarts/lib/component/dataZoom'
// import 'echarts/lib/chart/radar'
// import 'echarts/lib/chart/sankey'
// import 'echarts/lib/chart/map'
// import 'echarts/lib/chart/heatmap'
// import 'echarts/lib/component/geo'
// import 'echarts/lib/component/visualMap'

import 'echarts'
import 'echarts-wordcloud'
